'use strict';
const Scenario=(()=>{
 const $=id=>document.getElementById(id),fc=features=>({type:'FeatureCollection',features}),escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let map,data,view='spacing',popup,rows=[],lastCap=null,mapCap=null,capTimer;
 const capValue=()=>Number($('capPercent').value);
 const distanceValue=()=>Number($('distanceFeet').value);
 const measurementKey=()=>(!$('spacingMeasurement').checked?'border':'centroid')+'_'+($('blockAllLicensed').checked?'all':'nonresident');
 const measurementName=()=>!$('spacingMeasurement').checked?'Border-to-border':'Centroid-to-centroid';
 const viewName=()=>view==='spacing'?`${distanceValue().toLocaleString()}-foot spacing`:view==='cap'?`${capValue()}% cap`:`${distanceValue().toLocaleString()}-ft spacing + ${capValue()}% cap`;
 function recalculate(){const percentage=capValue(),signature=`${percentage}:${distanceValue()}:${measurementKey()}:${$('parcelSizePercentile').value}`;if(signature===lastCap)return;lastCap=signature;const areas=new Map(data.neighborhoods.features.map(f=>[f.properties.area_id,f.properties]));
  for(const p of areas.values()){p.cap_limit=Math.floor(p.residential*Math.round(percentage*10)/1000);p.cap_over_existing=Math.max(0,p.current_residential-p.cap_limit);p.cap_added=0;p.mixed_added=0;p.spacing_added=0;}
  const size=data.parcel_sizes,pct=Number($('parcelSizePercentile').value),maxSize=Math.abs(pct-size.default_percentile)<.00001?size.default_max_m2:size.residential_sizes_m2[Math.max(0,Math.ceil(pct/100*size.residential_sizes_m2.length)-1)],eligible=id=>size.areas_m2[id]!=null&&size.areas_m2[id]<=maxSize;const model=data.models[measurementKey()],pattern=model.patterns.patterns[String(distanceValue())].filter(eligible),selected=new Set(pattern),pointMap=new Map(data.points.features.map(f=>[f.properties.parcel,f.properties])),ranks=new Map(),areaRank=new Map();
  for(const id of pattern){const area=pointMap.get(id)?.neighborhood,n=(areaRank.get(area)||0)+1;areaRank.set(area,n);ranks.set(id,n);}
  let capAdded=0,mixedAdded=0;const capRanks=new Map(),capCounts=new Map();for(const f of data.points.features.filter(f=>f.properties.cap_rank>0&&eligible(f.properties.parcel)).sort((a,b)=>a.properties.cap_rank-b.properties.cap_rank)){const p=f.properties,n=(capCounts.get(p.neighborhood)||0)+1;capCounts.set(p.neighborhood,n);capRanks.set(p.parcel,n);}
  for(const f of data.points.features){const p=f.properties,a=areas.get(p.neighborhood),room=a?Math.max(0,a.cap_limit-a.current_residential):0;p.spacing=selected.has(p.parcel);p.blocker=p.current&&($('blockAllLicensed').checked||p.nonresident);f.geometry.coordinates=data.parcel_centroids[p.parcel];p.cap=!!a&&capRanks.has(p.parcel)&&capRanks.get(p.parcel)<=room;p.mixed=!!a&&p.spacing&&ranks.get(p.parcel)<=room;if(p.spacing&&a)a.spacing_added++;if(p.cap){a.cap_added++;capAdded++;}if(p.mixed){a.mixed_added++;mixedAdded++;}}
  for(const f of data.plots.features){const p=pointMap.get(f.properties.parcel);f.properties.cap=p.cap;f.properties.mixed=p.mixed;f.properties.spacing=p.spacing;f.properties.blocker=p.blocker;}
  const s=data.summary;
  for(const p of areas.values())for(const name of ['spacing','cap','mixed']){p[name+'_total']=p.current_residential+p[name+'_added'];p[name+'_percent']=p.residential?100*p[name+'_total']/p.residential:null;}
  for(const name of ['spacing','cap','mixed']){s[name+'_additions']=[...areas.values()].reduce((n,p)=>n+p[name+'_added'],0);s[name+'_percent']=100*(s.current_residential_plots+s[name+'_additions'])/s.residential;}
  $('parcelSizeValue').textContent=pct.toFixed(2)+'th percentile';
  $('parcelSizeNote').textContent=` Up to ${(maxSize*10.7639104).toLocaleString(undefined,{maximumFractionDigits:0})} sq ft. Largest current residential licensed parcel: ${size.largest_current_address} (${size.largest_current_parcel}), ${size.default_percentile.toFixed(2)}th percentile. Default size limit: 99th percentile. Existing licenses retained. Size does not verify a building is present; filtered examples are not re-packed.`;


 }
 function layoutPanels(){const bottom=Math.ceil($('modelResults').getBoundingClientRect().bottom),value=bottom+'px';if($('scenarioMap').style.top!==value){$('scenarioMap').style.top=value;$('scenarioPanel').style.top=(bottom+14)+'px';$('scenarioAdvanced').style.top=(bottom+14)+'px';map?.resize();}}
 window.addEventListener('resize',layoutPanels);
 function resultCards(){$('spacingMeasurementTop').checked=$('spacingMeasurement').checked;$('measurementValue').textContent=measurementName();$('measurementNotice').textContent=`${measurementName()} proxy Â· ${$('blockAllLicensed').checked?'All current licensed plots block additions (conservative)':'Only current non-resident permits block additions'}. Existing licenses are retained even when closer together. Neither proxy verifies the ordinanceâ€™s dwelling-unit spacing.`;$('distanceValue').textContent=distanceValue().toLocaleString()+' ft';$('spacingResultTitle').textContent='Separation model';$('spacingView').textContent=distanceValue().toLocaleString()+' ft';$('includeMixedAreasTop').checked=$('includeMixedAreas').checked;const s=data.summary;$('capPercentValue').textContent=capValue()+'%';$('capResultTitle').textContent='Percentage cap model';$('mixedResultTitle').textContent='Mixed: separation + cap';$('capView').textContent=`${capValue()}% cap`;for(const name of ['spacing','cap','mixed']){const n=s.current_residential_plots+s[name+'_additions'];$(name+'TotalResult').innerHTML=`${n.toLocaleString()} <small>residential plots</small>`;$(name+'PercentResult').textContent=ratio(s[name+'_percent']);$('result-'+name).classList.toggle('selected',view===name);$('selectResult-'+name).setAttribute('aria-pressed',String(view===name));if(name!=='spacing'){$('topCap-'+name).value=capValue();$('thumb-topCap-'+name).textContent=capValue()+'%';$('topCap-'+name).parentElement.style.setProperty('--position',(capValue()-.5)/19.5*100);}} $('mixedDistanceFeet').value=distanceValue();for(const id of ['distanceFeet','mixedDistanceFeet']){$('thumb-'+id).textContent=distanceValue().toLocaleString()+' ft';$(id).parentElement.style.setProperty('--position',(distanceValue()-400)/12);}layoutPanels();}
 const ratio=v=>v===null?'N/A':`${v.toFixed(2)}%`;
 function circle(point){const [lon,lat]=point,r=(distanceValue()*.3048)/6371008.8,phi=lat*Math.PI/180,lambda=lon*Math.PI/180,coords=[];for(let n=0;n<=64;n++){const theta=n*2*Math.PI/64,lat2=Math.asin(Math.sin(phi)*Math.cos(r)+Math.cos(phi)*Math.sin(r)*Math.cos(theta)),lon2=lambda+Math.atan2(Math.sin(theta)*Math.sin(r)*Math.cos(phi),Math.cos(r)-Math.sin(phi)*Math.sin(lat2));coords.push([lon2*180/Math.PI,lat2*180/Math.PI]);}return {type:'Feature',geometry:{type:'Polygon',coordinates:[coords]},properties:{}};}
 function details(p){return `<h3>${escape(p.name)}</h3><p>${p.residential.toLocaleString()} residential GIS plots<br>${p.current.toLocaleString()} current licensed plots (${p.current_residential.toLocaleString()} residential)</p><p><b>${distanceValue().toLocaleString()}-foot model: ${ratio(p.spacing_percent)}</b><br>${p.spacing_added.toLocaleString()} hypothetical additions + ${p.current_residential.toLocaleString()} existing residential licensed plots = ${p.spacing_total.toLocaleString()} Ã· ${p.residential.toLocaleString()} × 100</p><p><b>${capValue()}% cap model: ${ratio(p.cap_percent)}</b><br>${p.cap_added.toLocaleString()} hypothetical additions + ${p.current_residential.toLocaleString()} existing residential licensed plots = ${p.cap_total.toLocaleString()} Ã· ${p.residential.toLocaleString()} × 100<br>Neighborhood cap: ${p.cap_limit.toLocaleString()} plots.${p.cap_over_existing?` ${p.cap_over_existing} existing plots already above cap; no additions, no removals.`:''}</p><p><b>Mixed model: ${ratio(p.mixed_percent)}</b><br>${p.mixed_added.toLocaleString()} hypothetical additions + ${p.current_residential.toLocaleString()} existing = ${p.mixed_total.toLocaleString()} residential licensed plots. Both constraints apply.</p><p class="small">Hypothetical plot allocation, not actual Airbnb listings or verified licensing eligibility. The spacing build-out is feasible under the parcel-point model; maximum capacity has not been proven.</p>`;}
 function showArea(row){const bounds=new maplibregl.LngLatBounds();function visit(c){if(typeof c[0]==='number')bounds.extend(c);else c.forEach(visit);}visit(row.geometry.coordinates);map.fitBounds(bounds,{padding:innerWidth>700?{left:$('scenarioPanel').classList.contains('scenario-collapsed')?25:Math.ceil($('scenarioPanel').getBoundingClientRect().right)+20,right:50,top:25,bottom:50}:{top:Math.max(25,Math.min(map.getContainer().clientHeight-90,Math.ceil($('scenarioPanel').getBoundingClientRect().bottom-map.getContainer().getBoundingClientRect().top)+10)),bottom:35,left:25,right:25},maxZoom:14});popup?.remove();popup=new maplibregl.Popup({maxWidth:'340px'}).setLngLat(row.properties.anchor).setHTML(details(row.properties)).addTo(map);}
 function renderList(){const query=$('scenarioSearch').value.trim().toLowerCase(),container=$('scenarioAreas');container.replaceChildren();const sorted=rows.filter(r=>r.properties.name.toLowerCase().includes(query)).sort((a,b)=>(b.properties[view+'_percent']??-1)-(a.properties[view+'_percent']??-1)||a.properties.name.localeCompare(b.properties.name));for(const row of sorted){const p=row.properties,button=document.createElement('button');button.className='scenario-area';button.type='button';button.innerHTML=`<strong>${escape(p.name)} Â· ${ratio(p[view+'_percent'])}</strong><span class="values">${p.current_residential} current residential + ${p[view+'_added']} proposed / ${p.residential.toLocaleString()} residential plots</span><span class="values">Spacing: ${ratio(p.spacing_percent)} Â· ${capValue()}% cap: ${ratio(p.cap_percent)} Â· mixed: ${ratio(p.mixed_percent)}</span>${p.spacing_percent>capValue()?`<span class="values over-cap">Spacing example exceeds ${capValue()}%</span>`:''}${p.cap_over_existing?'<span class="values over-cap">Existing licenses already exceed cap</span>':''}`;button.onclick=()=>showArea(row);container.append(button);}if(!sorted.length)container.textContent='No matching neighborhoods.';$('areaResultNote').textContent=`${sorted.length} neighborhoods shown, sorted by ${viewName()} density. Mixed / multifamily areas ${$('includeMixedAreas').checked?'included':'hidden; use the blue toggle to show all sections'}. Overall totals include every city neighborhood.`;}
 function update(){if(!data||!map?.getSource('scenario-neighborhoods'))return;popup?.remove();popup=null;recalculate();resultCards();if(mapCap!==lastCap){map.getSource('scenario-points').setData(fc(data.points.features.filter(f=>f.properties.current||f.properties.spacing||f.properties.cap)));map.getSource('scenario-plots').setData(fc(data.plots.features.filter(f=>f.properties.current||f.properties.spacing||f.properties.cap)));mapCap=lastCap;}const s=data.summary,additional=s[view+'_additions'],total=s.current_residential_plots+additional;
 for(const name of ['spacing','cap','mixed'])$(name+'View').setAttribute('aria-pressed',String(view===name));$('additionLegend').textContent=`■ Hypothetical ${viewName()} additions`;$('additionLegend').style.color=view==='spacing'?'#ea580c':view==='cap'?'#2563eb':'#7c3aed';
 $('scenarioSummary').innerHTML=`<strong>${viewName()} example</strong><p>${s.current_residential_plots.toLocaleString()} current residential licensed plots + ${additional.toLocaleString()} hypothetical additions = ${total.toLocaleString()} Ã· ${s.residential.toLocaleString()} residential plots × 100 = ${ratio(s[view+'_percent'])}</p><p class="small">${s.current_plots-s.current_residential_plots} current nonresidential licensed plots excluded from density. All three citywide results stay visible above, including areas hidden by the mix toggle.</p><p class="small">${view==='spacing'?'Feasible sparse-first spacing example; not a proven maximum.':view==='cap'?'Cap-only replaces spacing. Limits round down; existing licenses above cap stay.':'Mixed applies both constraints to a capped subset of the spacing example. Freed space is not re-packed; a different arrangement may fit more.'}</p>`;
 rows=data.neighborhoods.features.filter(f=>{const p=f.properties,mix=data.mix.totals['0'][p.area_id];return ($('includeMixedAreas').checked||(mix&&p.residential>=100&&100*(mix.single_family+mix.duplex)/Object.values(mix).reduce((a,b)=>a+b,0)>=70&&100*(mix.single_family+mix.duplex)/p.residential>=80&&100*mix.unknown/Object.values(mix).reduce((a,b)=>a+b,0)<=15));}).map(f=>({...f,properties:{...f.properties,density:f.properties[view+'_percent'],label:`${f.properties.name}\n${ratio(f.properties[view+'_percent'])}`}}));
 map.getSource('scenario-neighborhoods').setData(fc(rows));map.getSource('scenario-labels').setData(fc(rows.map(r=>({type:'Feature',geometry:{type:'Point',coordinates:r.properties.anchor},properties:r.properties}))));
 const maxDensity=Math.max(.01,...rows.map(r=>r.properties.density||0));map.setPaintProperty('scenario-neighborhood-fill','fill-color',['interpolate',['linear'],['coalesce',['get','density'],0],0,view==='cap'?'#eff6ff':'#fff1f2',maxDensity/2,view==='cap'?'#60a5fa':'#ef4444',maxDensity,view==='cap'?'#1e3a8a':'#7f1d1d']);$('densityRedLegend').textContent=`Pale â†’ dark ${view==='cap'?'blue':'red'}: 0 â†’ ${ratio(maxDensity)} residential-plot density. Darkest neighborhoods have the highest modeled density among displayed areas.`;
 const allowed=['in',['get','neighborhood'],['literal',rows.map(r=>r.properties.area_id)]],proposed=['all',['==',['get',view],true],allowed],existing=['all',['==',['get','current'],true],allowed];map.setFilter('scenario-current',existing);map.setFilter('scenario-proposed',proposed);
 map.setLayoutProperty('scenario-current','visibility',$('showDots').checked&&$('showCurrent').checked?'visible':'none');map.setLayoutProperty('scenario-proposed','visibility',$('showDots').checked&&$('showAdditions').checked?'visible':'none');map.setPaintProperty('scenario-current','circle-color',['case',['get','blocker'],'#166534','#86efac']);map.setPaintProperty('scenario-proposed','circle-color',view==='spacing'?'#ea580c':view==='cap'?'#2563eb':'#7c3aed');
 const plotFilter=['any',...($('showCurrent').checked?[existing]:[]),...($('showAdditions').checked?[proposed]:[])];for(const id of ['scenario-plot-fill','scenario-plot-line','scenario-plot-pulse']){map.setFilter(id,plotFilter.length>1?plotFilter:['==',['get','parcel'],'__none__']);map.setLayoutProperty(id,'visibility',id!=='scenario-plot-fill'||$('showPlots').checked?'visible':'none');}map.setPaintProperty('scenario-plot-fill','fill-color',['case',existing,['case',['get','blocker'],'#166534','#86efac'],view==='spacing'?'#b45309':view==='cap'?'#1e40af':'#581c87']);
 map.setPaintProperty('scenario-plot-pulse','line-color',['case',existing,'#22c55e',view==='spacing'?'#f97316':view==='cap'?'#3b82f6':'#a855f7']);
 const validation=data.spacing_measurement_validation.patterns[measurementKey()][String(distanceValue())];
 $('spacingValidationNote').textContent=`${measurementName()}: new-to-new minimum ${validation.minimum_new_to_new_ft.toFixed(1)} ft; new-to-existing minimum ${validation.minimum_new_to_existing_ft.toFixed(1)} ft, against ${validation.blocking_existing_parcels} current licensed ${$('blockAllLicensed').checked?'':'non-resident '}parcels. This validates the modeled additions, not existingâ€“existing gaps. Parcel proxies and missing license locations limit legal interpretation.`;
 $('existingBlockerExplanation').textContent=$('blockAllLicensed').checked?'All green current licensed parcels block additions in this conservative example, including resident permits. Existing parcels are retained even if their borders touch.':'Dark-green non-resident permits block additions. Light-green resident / other permits do not block in this scenario. Existing permits are retained even if closer together.';
 $('residentPermitLegendSwatch').style.color=$('blockAllLicensed').checked?'#166534':'#86efac';
 $('showRings').disabled=view==='cap'||!$('spacingMeasurement').checked;map.getSource('scenario-rings').setData(fc(view!=='cap'&&$('spacingMeasurement').checked&&$('showRings').checked?data.points.features.filter(f=>(f.properties.blocker||f.properties[view])&&rows.some(r=>r.properties.area_id===f.properties.neighborhood)).map(f=>circle(f.geometry.coordinates)):[]));renderList();

 }
 async function init(){try{const names=['summary','neighborhoods','points','plots','city_boundary','spacing_patterns','spacing_extra_points','spacing_geometry_manifest','scenario_outcomes','measurement_extra_points','measurement_geometry_manifest','parcel_centroids','spacing_measurement_validation','parcel_sizes','cap_extension'];const loaded=await Promise.all(names.map(async n=>{const r=await fetch(`data/residential_scenarios/${n}.json`);if(!r.ok)throw Error(`${n}: HTTP ${r.status}`);return r.json();}));data=Object.fromEntries(names.map((n,i)=>[n,loaded[i]]));const extras=await Promise.all(data.spacing_geometry_manifest.chunks.map(async name=>{const response=await fetch('data/residential_scenarios/'+name);if(!response.ok)throw Error('Spacing geometry unavailable: '+name);return response.json();}));data.points.features.push(...data.spacing_extra_points.features);for(const extra of extras)data.plots.features.push(...extra.features);data.models={};await Promise.all(['centroid_all','centroid_nonresident','border_all','border_nonresident'].map(async key=>{const fetchJSON=async name=>{const response=await fetch(`data/residential_scenarios/${name}.json`);if(!response.ok)throw Error(name+' unavailable');return response.json();};const [patterns,outcomes]=await Promise.all([fetchJSON('spacing_patterns_'+key),fetchJSON('scenario_outcomes_'+key)]);data.models[key]={patterns,outcomes};}));const measurementExtras=await Promise.all(data.measurement_geometry_manifest.chunks.map(async name=>{const response=await fetch('data/residential_scenarios/'+name);if(!response.ok)throw Error('Measurement geometry unavailable');return response.json();}));data.points.features.push(...data.measurement_extra_points.features);for(const extra of measurementExtras)data.plots.features.push(...extra.features);data.points.features.push(...data.cap_extension.points.features);for(const f of data.points.features)f.properties.cap_rank=data.cap_extension.ranks[f.properties.parcel]||0;const capExtras=await Promise.all(data.cap_extension.chunks.map(async name=>{const r=await fetch('data/residential_scenarios/'+name);if(!r.ok)throw Error('Cap geometry unavailable');return r.json();}));for(const extra of capExtras)data.plots.features.push(...extra.features);const r=await fetch('data/gis_parcels/area_mix.json');if(!r.ok)throw Error('Parcel mix unavailable');data.mix=await r.json();
 $('parcelSizePercentile').step='any';$('parcelSizePercentile').value=99;
 $('modelMethod').textContent='Saved models use real projected parcel centroids or shortest polygon-to-polygon distances in EPSG:26915 with a 0.1% projection guard. Every new-to-new and new-to-existing distance is validated for the selected blocker set. These are greedy maximal examples, not proven maximums or verified dwelling-unit distances.';
 $('snapshotNote').textContent=`GIS capture: ${new Date(data.summary.gis_snapshot).toLocaleString('en-US',{timeZone:'America/New_York'})} ET. ${data.summary.unlocated_current_plots} current licensed plot IDs are absent from the city parcel subset; ${data.summary.unlocated_nonresident_plots} are non-resident, so missing blockers may affect the model. Neighborhoods without geometry assignments cannot be capped; ${data.summary.unassigned_candidates} unassigned candidates excluded from cap additions.`;
 recalculate();resultCards();
 map=new maplibregl.Map({container:'scenarioMap',center:[-94.56,39.1],zoom:11,style:{version:8,glyphs:'vendor/fonts/{fontstack}/{range}.pbf',sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'Â© OpenStreetMap contributors'}},layers:[{id:'basemap',type:'raster',source:'osm'}]}});map.addControl(new maplibregl.NavigationControl(),'bottom-right');map.addControl(new maplibregl.ScaleControl({maxWidth:180,unit:'imperial'}),'bottom-right');map.on('load',()=>{
 for(const [name,value] of [['scenario-neighborhoods',fc([])],['scenario-labels',fc([])],['scenario-points',fc(data.points.features.filter(f=>f.properties.current||f.properties.spacing||f.properties.cap))],['scenario-plots',fc(data.plots.features.filter(f=>f.properties.current||f.properties.spacing||f.properties.cap))],['scenario-rings',fc([])],['scenario-city',data.city_boundary]])map.addSource(name,{type:'geojson',data:value});
 map.addLayer({id:'scenario-neighborhood-fill',type:'fill',source:'scenario-neighborhoods',paint:{'fill-opacity':.35,'fill-color':['interpolate',['linear'],['coalesce',['get','density'],0],0,'#dbeafe',5,'#f59e0b',10,'#b91c1c']}});map.addLayer({id:'scenario-neighborhood-line',type:'line',source:'scenario-neighborhoods',paint:{'line-color':'#172b3b','line-width':2,'line-opacity':.85}});
 map.addLayer({id:'scenario-plot-fill',type:'fill',source:'scenario-plots',paint:{'fill-color':'#15803d','fill-opacity':.88}});map.addLayer({id:'scenario-plot-line',type:'line',source:'scenario-plots',paint:{'line-color':'#050505','line-width':['interpolate',['linear'],['zoom'],10,.2,13,.6,16,1.2,19,1.6],'line-opacity':['interpolate',['linear'],['zoom'],10,0,12,.15,14,.75,16,1]}});
 map.addLayer({id:'scenario-plot-pulse',type:'line',source:'scenario-plots',paint:{'line-color':'#ffffff','line-width':2,'line-opacity':.7,'line-blur':.4}});
 map.addLayer({id:'scenario-ring-line',type:'line',source:'scenario-rings',paint:{'line-color':'#ea580c','line-opacity':.3,'line-width':1}});
 for(const [id,color,radius] of [['scenario-proposed','#ea580c',4],['scenario-current','#15803d',5]])map.addLayer({id,type:'circle',source:'scenario-points',paint:{'circle-color':color,'circle-radius':['interpolate',['linear'],['zoom'],9,2,13,radius,17,radius*2],'circle-stroke-color':'#ffffff','circle-stroke-width':1}});
 map.addLayer({id:'scenario-city-halo',type:'line',source:'scenario-city',paint:{'line-color':'#ffffff','line-width':9,'line-opacity':.95}});
 map.addLayer({id:'scenario-city-outline',type:'line',source:'scenario-city',paint:{'line-color':'#172b3b','line-width':4.5,'line-opacity':1}});
 map.addLayer({id:'scenario-area-labels',type:'symbol',source:'scenario-labels',minzoom:10,layout:{'text-field':['get','label'],'text-font':['Noto Sans Regular'],'text-size':12,'text-max-width':15},paint:{'text-color':'#172b3b','text-halo-color':'#ffffff','text-halo-width':2}});
 map.on('click','scenario-area-labels',event=>{const row=rows.find(r=>r.properties.area_id===event.features[0].properties.area_id);if(row)showArea(row);});
 for(const id of ['scenario-current','scenario-proposed','scenario-plot-fill'])map.on('click',id,event=>{const p=event.features[0].properties;popup?.remove();popup=new maplibregl.Popup().setLngLat(event.lngLat).setHTML(`<b>${escape(p.address)}</b><p>Parcel ${escape(p.parcel)}<br>${p.current?'Current licensed plot in saved permit inventory':'Hypothetical '+viewName()+' addition; not a listing or permit'}<br>${p.current?(p.nonresident?'Non-resident permit anchor':'No current non-resident permit identified'):''}</p>`).addTo(map);});
 const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)');$('animateScenarioPlots').checked=!reduceMotion.matches;
 let pulseFrame,pulseTick=0;
 function animatePlots(time){if(!map.getLayer('scenario-plot-pulse'))return;if(time-pulseTick>=65){pulseTick=time;const animate=$('animateScenarioPlots').checked&&!document.hidden,phase=(time%2400)/2400,zoom=map.getZoom(),strength=Math.max(0,Math.min(1,(zoom-10)/3));map.setPaintProperty('scenario-plot-pulse','line-width',animate?1+phase*12:2);map.setPaintProperty('scenario-plot-pulse','line-opacity',animate?(1-phase)*.7*strength:0);map.setPaintProperty('scenario-plot-fill','fill-opacity',animate?.83+.12*Math.sin(phase*Math.PI):.9);}pulseFrame=requestAnimationFrame(animatePlots);}
 pulseFrame=requestAnimationFrame(animatePlots);map.on('remove',()=>cancelAnimationFrame(pulseFrame));
 ParcelOutlines.init(map,{before:'scenario-plot-fill'});update();$('fitScenarioCity').click();});
 for(const id of ['showCurrent','showAdditions','showPlots','showRings','includeMixedAreas','showDots'])$(id).addEventListener('change',update);$('spacingView').onclick=()=>{view='spacing';update();};$('capView').onclick=()=>{view='cap';update();};$('mixedView').onclick=()=>{view='mixed';update();};$('capPercent').addEventListener('input',event=>{if(!data?.models)return;view=event.detail?.owner||'cap';recalculate();resultCards();clearTimeout(capTimer);capTimer=setTimeout(update,120);});$('scenarioSearch').addEventListener('input',renderList);
 for(const name of ['spacing','cap','mixed']){
  $('selectResult-'+name).onclick=()=>{view=name;update();};
  $('result-'+name).addEventListener('click',event=>{if(event.target.closest('input,.slider-thumb-value,.result-select,.option-help'))return;view=name;update();});
 }
 $('spacingMeasurementTop').addEventListener('change',()=>{$('spacingMeasurement').checked=$('spacingMeasurementTop').checked;update();});
 for(const name of ['cap','mixed'])$('topCap-'+name).addEventListener('input',event=>{$('capPercent').value=event.target.value;$('capPercent').dispatchEvent(new CustomEvent('input',{detail:{owner:name}}));});
 $('scenarioAdvanced').addEventListener('toggle',layoutPanels);
 $('toggleScenarioPanel').onclick=()=>{const collapsed=$('scenarioPanel').classList.toggle('scenario-collapsed');$('scenarioPanelBody').hidden=collapsed;$('toggleScenarioPanel').textContent=collapsed?'Show':'Hide';$('toggleScenarioPanel').setAttribute('aria-expanded',String(!collapsed));layoutPanels();};
 $('distanceFeet').addEventListener('input',event=>{if(!data?.models)return;view=event.detail?.owner||'spacing';recalculate();resultCards();clearTimeout(capTimer);capTimer=setTimeout(update,120);});
 $('mixedDistanceFeet').addEventListener('input',event=>{$('distanceFeet').value=event.target.value;$('distanceFeet').dispatchEvent(new CustomEvent('input',{detail:{owner:'mixed'}}));});
 for(const id of ['spacingMeasurement','blockAllLicensed','parcelSizePercentile'])$(id).addEventListener('input',update);
 for(const id of ['distanceFeet','mixedDistanceFeet','topCap-cap','topCap-mixed']){const handle=$('thumb-'+id),slider=$(id);handle.tabIndex=0;handle.setAttribute('role','slider');handle.setAttribute('aria-label',slider.getAttribute('aria-label')||'Adjust '+id);handle.addEventListener('pointerdown',event=>{event.preventDefault();handle.setPointerCapture(event.pointerId);const start=event.clientX,value=Number(slider.value),width=slider.getBoundingClientRect().width;const move=e=>{const step=Number(slider.step)||1,min=Number(slider.min),max=Number(slider.max);slider.value=Math.max(min,Math.min(max,Math.round((value+(e.clientX-start)*(max-min)/width)/step)*step));slider.dispatchEvent(new Event('input',{bubbles:true}));};const stop=()=>{handle.removeEventListener('pointermove',move);handle.removeEventListener('pointerup',stop);handle.removeEventListener('pointercancel',stop);};handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',stop);handle.addEventListener('pointercancel',stop);});handle.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight'].includes(event.key))return;event.preventDefault();slider.value=Number(slider.value)+(event.key==='ArrowRight'?1:-1)*Number(slider.step);slider.dispatchEvent(new Event('input',{bubbles:true}));});}
 $('includeMixedAreasTop').addEventListener('change',()=>{$('includeMixedAreas').checked=$('includeMixedAreasTop').checked;update();});
 $('fitScenarioCity').onclick=()=>{if(!map||!data?.city_boundary)return;const bounds=new maplibregl.LngLatBounds();function visit(c){if(typeof c[0]==='number')bounds.extend(c);else c.forEach(visit);}data.city_boundary.features.forEach(f=>visit(f.geometry.coordinates));map.fitBounds(bounds,{padding:innerWidth>700?{left:$('scenarioPanel').classList.contains('scenario-collapsed')?25:Math.ceil($('scenarioPanel').getBoundingClientRect().right)+20,right:50,top:25,bottom:40}:{left:25,right:25,top:Math.max(25,Math.min(map.getContainer().clientHeight-90,Math.ceil($('scenarioPanel').getBoundingClientRect().bottom-map.getContainer().getBoundingClientRect().top)+10)),bottom:25}});};
 $('downloadScenarioCounts').onclick=()=>{const fields=['name','residential','current_residential','spacing_added','spacing_total','spacing_percent','cap_limit','cap_added','cap_total','cap_percent','mixed_added','mixed_total','mixed_percent'];const quote=v=>'\"'+String(v??'').replace(/\"/g,'\"\"')+'\"';const lines=[['spacing_measure','blocker_set','max_parcel_size_percentile','separation_feet','cap_setting_percent',...fields]];for(const f of data.neighborhoods.features)lines.push([measurementName(),$('blockAllLicensed').checked?'all_current_licensed':'current_nonresident',$('parcelSizePercentile').value,distanceValue(),capValue(),...fields.map(k=>f.properties[k])]);const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.map(row=>row.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`kansas-city-scenarios-${distanceValue()}-feet-${capValue()}-percent.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 }catch(error){console.error(error);$('scenarioSummary').textContent='Unable to load scenarios: '+error.message;}}
 document.querySelectorAll('.option-help').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();$('optionHelpText').textContent=button.dataset.explanation;$('optionHelpDialog').showModal();}));$('closeOptionHelp').onclick=()=>$('optionHelpDialog').close();$('optionHelpDialog').addEventListener('click',event=>{if(event.target===$('optionHelpDialog')){const r=event.target.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)event.target.close();}});
 init();return {get map(){return map;},get data(){return data;},get view(){return view;},get rows(){return rows;}};
})();
