'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let datasets={},page=0;
function actualPermitValues(item){
  const matches=Array.isArray(item?.matched_permits)?item.matched_permits:Array.isArray(item?.matched_permit_numbers)?item.matched_permit_numbers.map(value=>({permit_number:value})):[];
  return matches.map(p=>String(p?.permit_number ?? p?.permit ?? p?.id ?? p?.number ?? '').trim()).filter(Boolean);
}
function render(){const kind=$('kind').value,q=$('query').value.toLowerCase(),rows=datasets[kind].filter(r=>JSON.stringify(r).toLowerCase().includes(q));const last=Math.max(0,Math.ceil(rows.length/100)-1);page=Math.min(page,last);$('count').textContent=`${rows.length.toLocaleString()} records · Page ${page+1} of ${last+1}`;$('prev').disabled=!page;$('next').disabled=page===last;$('download').href=`data/${kind}.csv`;
const columns=kind==='listings'?['Listing','Host','Guests','Bedrooms','Over capacity','License status','Hotel screening','Actual licenses','Amenities','Location']:['Permit number','Status','Source status'];$('head').innerHTML='<tr>'+columns.map(c=>`<th>${esc(c)}</th>`).join('')+'</tr>';
$('body').innerHTML=rows.slice(page*100,(page+1)*100).map(r=>{const values=kind==='listings'?[`<a href="${esc(r.url)}" target="_blank" rel="noopener">${esc(r.title||r.listing_id)}</a>`,esc(r.host_name),esc(r.guests??'Unknown'),esc(r.bedrooms??'Unknown'),esc(r.over_capacity??'Unknown'),esc(r.cancelled_permit_at_permitted_address?'Valid · current permit at same property; listed permit cancelled':r.noncurrent_permit_at_permitted_address?(r.registration_class==='expired'?'Likely permitted · Listed permit expired, property permit renewed':'Current permit at same property · listed permit non-current; unit unverified'):r.registration_class==='unmatched'?'Potentially licensed: permit does not show up in license list':r.likely_unlicensed_number===true?'Likely unlicensed':r.registration_class==='current'?'Number found in PDF':r.registration_class||r.license_status),r.likely_hotel?'<span class="hotel-notice">Likely hotel</span>':'N/A',esc(actualPermitValues(r).join(', ')||'N/A'),esc(Object.keys(r.amenities).join(', ')),esc(r.point?r.location_name:'Awaiting location')]:[esc(r.permit_number||'Unavailable'),esc(r.status),esc(r.source_status)];return '<tr>'+values.map(v=>`<td>${v}</td>`).join('')+'</tr>';}).join('');}
Promise.all(['listings','permits'].map(async k=>{const r=await fetch(`data/${k}.json`);if(!r.ok)throw Error(r.status);datasets[k]=await r.json();})).then(async()=>{const parts=await Promise.all(['data/permit_location_points.json','data/permit_parcels.geojson','data/permit_property_parcels.geojson'].map(async url=>{try{const r=await fetch(url);return r.ok?await r.json():{features:[]};}catch{return {features:[]};}}));datasets.propertyLocations={features:parts.flatMap(p=>p.features||[])};try{const response=await fetch('data/permit_saved_details.json');if(response.ok)datasets.permitDetails=await response.json();}catch{}PermitProperties.prepare(datasets.listings,datasets.permits,datasets.propertyLocations,datasets.permitDetails);render();$('kind').onchange=$('query').oninput=()=>{page=0;render();};$('prev').onclick=()=>{page--;render();};$('next').onclick=()=>{page++;render();};}).catch(e=>$('count').textContent=`Unable to load records: ${e.message}`);
