from playwright.sync_api import sync_playwright
with sync_playwright() as p:
 b=p.chromium.launch(channel='msedge',headless=False);page=b.new_page(viewport={'width':1500,'height':1000});errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
 page.route('https://unpkg.com/maplibre-gl@3.6.0/dist/maplibre-gl.js',lambda r:r.fulfill(path='residential_neighborhood_impact/vendor/maplibre-gl.js',content_type='application/javascript'))
 page.goto('http://localhost:8765/worst_case.html');page.wait_for_function("typeof Scenario!=='undefined'&&Scenario.rows.length>0",timeout=90000)
 assert page.input_value('#parcelSizePercentile')=='99';assert page.is_checked('#includeMixedAreasTop');assert not page.locator('#scenarioAdvanced').evaluate('e=>e.open');page.locator('#scenarioAdvanced summary').click();page.uncheck('#includeMixedAreasTop');assert not page.is_checked('#includeMixedAreas');page.check('#includeMixedAreasTop');page.locator('#scenarioAdvanced summary').click()
 assert not page.is_checked('#spacingMeasurement');assert page.get_attribute('#spacingMeasurement','type')=='checkbox'
 assert page.evaluate("getComputedStyle(document.body).userSelect")=='none'
 assert page.evaluate("Scenario.data.points.features.filter(f=>!f.properties.current&&(f.properties.spacing||f.properties.cap||f.properties.mixed)).every(f=>Scenario.data.parcel_sizes.areas_m2[f.properties.parcel]<=Scenario.data.parcel_sizes.default_max_m2)")
 before=page.input_value('#mixedDistanceFeet');box=page.locator('#thumb-mixedDistanceFeet').bounding_box();page.mouse.move(box['x']+box['width']/2,box['y']+box['height']/2);page.mouse.down();page.mouse.move(box['x']+box['width']/2+80,box['y']+box['height']/2,steps=8);page.mouse.up();page.wait_for_timeout(350);assert page.input_value('#mixedDistanceFeet')!=before;assert page.evaluate('Scenario.view')=='mixed'
 before=page.input_value('#topCap-mixed');box=page.locator('#thumb-topCap-mixed').bounding_box();page.mouse.move(box['x']+box['width']/2,box['y']+box['height']/2);page.mouse.down();page.mouse.move(box['x']+box['width']/2-70,box['y']+box['height']/2,steps=6);page.mouse.up();page.wait_for_timeout(350);assert page.input_value('#topCap-mixed')!=before
 page.eval_on_selector('#parcelSizePercentile',"e=>{e.value=75;e.dispatchEvent(new Event('input'))}");page.wait_for_timeout(300)
 assert page.evaluate("(()=>{const d=Scenario.data,sz=d.parcel_sizes,max=sz.residential_sizes_m2[Math.ceil(.75*sz.residential_sizes_m2.length)-1];return d.points.features.filter(f=>!f.properties.current&&(f.properties.spacing||f.properties.cap||f.properties.mixed)).every(f=>sz.areas_m2[f.properties.parcel]<=max)})()")
 assert page.evaluate("(()=>{const d=Scenario.data;return ['spacing','cap','mixed'].every(k=>d.summary[k+'_additions']===d.points.features.filter(f=>!f.properties.current&&f.properties[k]).length)})()")
 page.check('#spacingMeasurement');assert page.locator('#measurementValue').inner_text()=='Centroid-to-centroid';page.uncheck('#spacingMeasurement');assert page.locator('#measurementValue').inner_text()=='Border-to-border'
 page.screenshot(path='audits/scenario_size_controls_preview.png');page.set_viewport_size({'width':390,'height':844});page.wait_for_timeout(500);assert page.locator('#topCap-mixed').bounding_box()['y']>page.locator('#mixedDistanceFeet').bounding_box()['y']+25;assert page.locator('#scenarioPanel').bounding_box()['y']>page.locator('#modelResults').bounding_box()['y']+page.locator('#modelResults').bounding_box()['height'];page.screenshot(path='audits/scenario_size_controls_mobile.png');assert not errors,errors
 print({'drag_numbers':'passed','size_filter_and_counts':'passed','border_default':'passed','desktop_mobile':'passed','errors':errors});b.close()
